# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
#  - id: libfarmfa
#    dir: libfarmfa
#    binary: libfarmfa
#    env:
#      - CGO_ENABLED=1
#    goos:
#      - darwin
#      - android
#    goarch:
#      - arm
#      - arm64
#    goarm:
#      - 7
#    buildmode: c-shared
#    ldflags: -s -w
#    overrides:
#      - goos: android
#        goarch: arm
#        goarm: 7
#        env:
#          - CC=armv7a-linux-androideabi33-clang
#      - goos: android
#        goarch: arm64
#        env:
#          - CC=aarch64-linux-android33-clang
archives:
  - id: cli
    builds:
      - cli
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_farmfacli_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
#  - id: lib
#    builds:
#      - libfarmfa
#    format: tar.gz
#    name_template: >-
#      {{ .ProjectName }}_libfarmfa_
#      {{- title .Os }}_
#      {{- if eq .Arch "amd64" }}x86_64
#      {{- else if eq .Arch "386" }}i386
#      {{- else }}{{ .Arch }}{{ end }}
#      {{- if .Arm }}v{{ .Arm }}{{ end }}
#    format_overrides:
#      - goos: windows
#        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
